from pydantic import BaseModel, Field

class KubernetesDiagnosis(BaseModel):
    """
    Structured diagnosis report generated by the AI Kubernetes SRE agent.
    """
    root_cause: str = Field(
        ..., 
        description="A concise, high-level summary of the primary root cause"
    )
    explanation: str = Field(
        ..., 
        description="Detailed, correlated SRE explanation of the failure showing how logs, events, and pod states match up"
    )
    fix: str = Field(
        ..., 
        description="Actionable, practical suggested fix to resolve the issue"
    )
    kubectl_command: str = Field(
        ..., 
        description="Specific kubectl command(s) the developer can run directly to implement or investigate the fix"
    )
    prevention: str = Field(
        ..., 
        description="Practical prevention recommendation or long-term advice to avoid this failure in the future"
    )
    confidence: int = Field(
        ..., 
        description="Confidence score from 0 to 100 representing the engine's level of certainty"
    )
